[package]
name = "pigment-db"
version = "0.8.2"
edition = "2021"


[dependencies]
crc32fast = "1.2.1"
dashmap = "3.11.10"
faster-hex = "0.9.0"
memmap = "0.7.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_bytes = "0.11.5"
bincode = "1.3.3"
log = "0.4.11"
